channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - cuda
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - pyaudio
  - transformers
  - accelerate
